### ISSUE TITLE
How to install to orocommerce 3.1.x

### ISSUE THREAD

**Issue by kkrieger85** [taymiya/orocommerce#2]
Please add a how to install on orocommerce v 3.1.

**Comment by taymiya** [comment]
php bin/console oro:migration:load --force
php bin/console oro:migration:data:load
php bin/console oro:entity-extend:update-config
php bin/console oro:entity-extend:update-schema
php bin/console oro:entity-extend:cache:clear
php bin/console oro:entity-config:update
php bin/console oro:entity-config:cache:clear
php bin/console oro:translation:load
php bin/console cache:clear

and publish assets ...
