### ISSUE TITLE
Unknown column 'parent_entity_class'  (orocommerce 3.1.x)

### ISSUE THREAD

**Issue by kkrieger85** [taymiya/orocommerce#3]
I tried to save global header settings.

```

Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'INSERT INTO oro_attachment_file (serialized_data, filename, extension, mime_type, original_filename, file_size, parent_entity_class, parent_entity_id, parent_entity_field_name, created_at, updated_at, owner_user_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["Tjs=", "5d284c20973fc619749269.png", "png", "image\/png", "Logo-kkrieger-1024x473.png", 157024, null, null, null, "2019-07-12 09:00:16", "2019-07-12 09:00:16", 1]:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'parent_entity_class' in 'field list'" at /var/www/share/orocommerce-project-mde/production/releases/oroapp-3.1.6/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 79

```

**Comment by kkrieger85** [comment]
As far as I understand the process, this happens if I try to add/upload an image. I tried *.jpg as well as *.png

**Comment by taymiya** [comment]
So In OroCommerce 3.1.1  - Taymiya PDF Manager support *.png and *.jpg for global header logo
See images
![AwesomeScreenshot-Configuration-System-2019-07-12-14-07-19](https://user-images.githubusercontent.com/29682277/61133716-e59fc600-a4b5-11e9-928b-5c26e33ea2f6.png)
![AwesomeScreenshot-Configuration-System-2019-07-12-14-07-88](https://user-images.githubusercontent.com/29682277/61133717-e59fc600-a4b5-11e9-9db6-b4f5cf78b54d.png)

**Comment by kkrieger85** [comment]
Issue is/was not related to PDF Manager.
